# Generated by Django 5.0.7 on 2024-07-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('water_8_cups', '물 8컵 마시기'), ('breakfast', '아침 식사하기'), ('salad', '샐러드 먹기'), ('nuts', '견과류 먹기'), ('fish', '생선 먹기'), ('vegetable_juice', '야채주스 마시기'), ('fermented_food', '발효식품 먹기'), ('protein', '단백질 먹기'), ('cardio', '유산소 운동 하기'), ('strength_training', '근력 운동하기'), ('stretching', '스트레칭하기'), ('meditation', '명상하기'), ('therapeutic_bath', '목욕하기'), ('massage', '마사지 받기'), ('sleep_7_hours', '7시간 이상 잠자기')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItemDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='todo.todoitem')),
            ],
            options={
                'unique_together': {('item', 'date')},
            },
        ),
    ]
